diabetes <- read.csv("~/Documents/Capstone/Data Files/diabetes.csv")
str(diabetes)
for (i in 2:6) {
diabetes <- diabetes[-which(diabetes[,i] ==0), ]}
str(diabetes)
hist(diabetes$Pregnancies)
hist(diabetes$Glucose)
hist(diabetes$BloodPressure)
hist(diabetes$SkinThickness)
hist(diabetes$Insulin)
hist(diabetes$BMI)
hist(diabetes$DiabetesPedigreeFunction)
hist(diabetes$Age)
X <- cor(diabetes)
corrplot(X, method = "circle")
set.seed(140)
training_set <- sort(sample(nrow(diabetes), nrow(diabetes)*.7))
diabetes_train <- diabetes[training_set,]
diabetes_test <- diabetes[-training_set,]
model <- glm(Outcome~.,data=diabetes_train,family = binomial(link='logit'))
summary(model)
model2 <- glm(Outcome~Glucose + BMI + DiabetesPedigreeFunction,data=diabetes_train,family = binomial(link='logit'))
summary(model2)
predictions <- predict(model2,newdata=diabetes_test,type="response")
predictions <- round(predictions)
mean(predictions==diabetes_test$Outcome)
p <- predict(model2, diabetes_test, type="response")
pr <-prediction(p, diabetes_test$Outcome)
prf <- performance(pr, measure = "tpr", x.measure = "fpr")
plot(prf)
auc = performance(pr, measure = "auc")
auc = auc@y.values[[1]]
print(paste("Logistic Regression Model Accuracy", auc))
model3 <- randomForest(as.factor(Outcome) ~ Pregnancies+Glucose+BloodPressure+SkinThickness+Insulin+BMI+DiabetesPedigreeFunction+Age, data=diabetes_train, importance=TRUE, ntree=2000)
varImpPlot(model3)
predictions2 <-predict(model3,diabetes_test,type="response")
table(predictions2,diabetes_test$Outcome)
RFAccuracy <-(65+27)/nrow(diabetes_test)
print(paste("Random Forest Model Accuracy", RFAccuracy))
